### ISSUE TITLE
convert VALIDATOR_ADDRESS to EIP-55 explicitly before usage 

### ISSUE THREAD

**Issue by akolotov** [poanetwork/bridge-nodejs#12]
If an address in `VALIDATOR_ADDRESS` is noted in lower case it will lead to the situation when
https://github.com/poanetwork/bridge-nodejs/blob/a23ecb78572f3e1928d9129eff8d4118b2618b57/src/processCollectedSignatures.js#L72
will always fail since `authorityResponsibleForRelay` is returned with EIP-55 formatting.

So in order to have the code independent from the format of address provided in configuration file it makes sense to format `VALIDATOR_ADDRESS` as per EIP-55 explicitly before `if`-statement stated above.

**Comment by rstormsf** [comment]
Tip:
https://web3js.readthedocs.io/en/1.0/web3-utils.html#tochecksumaddress

```js
Web3Utils.toChecksumAddress(address)
```
