### ISSUE TITLE
Incorrect handling of transactions in case of insufficient funds

### ISSUE THREAD

**Issue by akolotov** [poanetwork/bridge-nodejs#13]
If a validator has no enough funds to handle transaction the bridge is trying to send transaction, fails and updating the database:

```
Found 1 Deposits on Home Network
Error! { code: -32010,
  message: 'Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 2314865000000000 and got: 0.' }
1 '# processing deposit' '0xa85bb9dca943978bff7054db8172cc7c382cb321364e3b7fd3f137d30bb51983' undefined
writing db deposits 91
```

It leads to necessity to stop the bridge, roll back the changes in database manually and start the bride again after the validator balance refill.

So, in order to handle 'insufficient funds' issue properly the bridge should:
1. check balance of validator on Home and Foreign side as soon as the corresponding event (`Deposit`, `CollectedSignaturs` or `Withdraw`) to relay transaction is received
2. only if the balance is positive, relay transaction
3. otherwise the bridge must stop operations in the corresponding direction until the validator balance is refilled. **No database updates must be done** for the corresponding event type.

**Comment by rstormsf** [comment]
once funds are insuffiecient, the whole bridge should be probably crashed and stopped. and no futher db saves 

I guess in sendTx.js we should handle this case and make a `throw`

**Comment by akolotov** [comment]
@rstormsf do you think it make sense to crash? even if another side still has funds to process transactions?
Imagine, if we have no enough funds on Foreign side, we still are able to relay withdrawals to Home since it does not require transactions on Home side.

But with multi-workers architecture it will be worth to stop (or suspend) the corresponding worker, other workers are still running (since they even can be on different system).

**Comment by rstormsf** [comment]
@akolotov it  will pile up the whole queue. If bridge doesn't have funds on some side, all workers related to that side should be stopped

**Comment by akolotov** [comment]
In this case it is necessary to think how to communicate this if the workers are located on different physical systems.

**Comment by fvictorio** [comment]
It seems to me that the best option is to just put it back to the queue. Adding communication between workers may break the architecture. Besides, this seems like a responsibility of the monitoring tool, that should emit an alert if a validator doesn't have enough funds. I don't have numbers, but I'd guess that rabbit can handle a very large number of enqueued messages before that being an issue.

The worker should stop working, though, since there's nothing it can do.

**Comment by akolotov** [comment]
@fvictorio I am ok with it

**Comment by rstormsf** [comment]
@fvictorio makes sense. Lets stop the worker and final error message could be to explain that it had insufficient funds.
