### ISSUE TITLE
Configurable polling time

### ISSUE THREAD

**Issue by akolotov** [poanetwork/bridge-nodejs#14]
The bridge invokes tasks (`processDeposits`, `processCollectedSignatures` and `processWithdraw`) every second:
https://github.com/poanetwork/bridge-nodejs/blob/a23ecb78572f3e1928d9129eff8d4118b2618b57/src/start.js#L42-L47
It is too often even for chains like POA since a new block appeared only once in 5 seconds.

So, it makes sense
1. to configure the polling timeout in the configuration file;
2. to have different timeouts for Home and Foreign chains:
  * `processDeposits` and `processCollectedSignatures` should listen events with the timeout `HOME_POLLING_INTERVAL`
  * `processWithdraw` should listen events with the timeout `FOREIGN_POLLING_INTERVAL`

**Comment by rstormsf** [comment]
My logic was that those processing events could take longer than that, so I did it every second.
The issue will be redundant as soon as we move to queue service

**Comment by akolotov** [comment]
@rstormsf I do think that it is worth to not poll the node every second even in new architecture: workers listening for events could fetch new events also with configurable interval as it is described above.
