### ISSUE TITLE
a switch of 1 xdai to dai did not work.

### ISSUE THREAD

**Issue by kropple** [poanetwork/bridge-nodejs#151]
i sent 1 xdai to the bridge:
https://blockscout.com/poa/xdai/tx/0x2bc754f2d6c03857b281b551a7ea95ce1f29a8e7d73a6398098636ba3a4b43a9

but i did not get the DAI on eth mainnet.

then i sent another 2 xDAI to the bridge:
https://blockscout.com/poa/xdai/tx/0x634e78fd281b1c5694b4ce555c5904b2fdc38536f4847eb2591a9b23c87ed41f
then instantly the 2 dai came on mainnet:
https://etherscan.io/tx/0x4e1f4beea0544be966e2da68d1059858a66e84f9f1f30f3ec0c9ade22acd4c1f

is 1 DAI to small, or is it gonna come later?

**Comment by akolotov** [comment]
It should be OK now: https://etherscan.io/tx/0xcbaef4580a613124f333b23bfe5e0f94c2a59ffa018235f432761a78541c2086

Please use [the forum](https://forum.poa.network/c/xdai-chain/17) to notify about such kind of issues next time

**Comment by kropple** [comment]
thanks, i was more curious about WHY, the 1 dai would not kill me, 
but when providing the xdai-bridge to my users it would be nice to know about such quirks and the reasons, so i can document accordingly

thanks for your quick help!!!

**Comment by akolotov** [comment]
> thanks, i was more curious about WHY, the 1 dai would not kill me,
> but when providing the xdai-bridge to my users it would be nice to know about such quirks and the reasons, so i can document accordingly

Well, connection to a Mainnet RPC node one of the validator communicating with went down. We switched this validator's oracle to another RPC node so far. 

If it looks like that something is wrong with the xDai bridge you can point your user to the xDai bridge monitor service: https://bridge-monitoring.poa.net/xdai/eventsStats. Where they can find a transaction if is stuck on the bridge: 
  * The `onlyInHomeDeposits` list will no be empty if the xDai was not transferred to Dai.
  * The `onlyInForeignWithdrawals` list will not be empty if the Dai was not transferred to xDai. Currently, it has one transaction which appeared long time ago, before the bridge was switched from Sai to Dai.
