### ISSUE TITLE
New mode of the bridge to relay ERC20 tokens (erc20-to-erc20)

### ISSUE THREAD

**Issue by akolotov** [poanetwork/bridge-nodejs#18]
It is necessary to develop additional sub-processes (similar to `processDeposits`, `processCollectedSignatures` and `processWithdraw`) in order to allow ERC20 to ERC20 bridging.

Here is description of ERC20 to ERC20 bridging idea:
1. Home side is POA network, it will keep ERC677 compliant token. `HomeBridge` contract is deployed here.
2. Foreign side is an EVM based network, it will keep ERC20 compliant token. `ForeignBridge` contract is deployed here.
3. The bridge must listen `Transfer()` events on the address of the ERC20 token on Foreign side and filter transactions transfering tokens to `ForeignBridge` contract.
4. As soon as the corresponding `Transfer()` is appeared, the bridge must send `deposit()` transaction to `HomeBridge` contract: it means that the brdige validator apporves relaying of the token to POA network.
5. The bridge must listen `Withdraw()` events on the address of `HomeBridge` contract.
6. As soon as the corresponding `Withdraw()` is appeared, the bridge must send `submitSignature()` to `HomeBridge` contract: it means that the bridge validator apporoves relaying of the token to Foreign network.
7. The bridge must listen `CollectedSignatures()` events on the address of `HomeBridge` contract.
8. As soon as the corresponding `CollectedSignatures()` is appeared, it checks that validator address from the event is the same as the address of the validator of the particular bridge instance and sends `withdraw()` to `ForeignBridge` contract: it performs actual relaying of the approved withdrawal to Foreign network.

In order to switch the bridge from _POA coin to POA20 token_ mode to _ERC20 to ERC20_ mode, the following configuration parameter could be used in `.env` file:
```
MODE="erc20-to-erc20"
```
Therefore:
* If the parameter is configured as presented above, the bridge will work in _ERC20 to ERC20_ mode.
* If the parameter is configured to have the value "poa-to-poa20" or there is no such parameter in the configuration file at all, the bridge will work in _POA coin to POA20 token_ mode.

**Comment by rstormsf** [comment]
Contracts are done in this branch:
https://github.com/poanetwork/poa-bridge-contracts/tree/erc20toErc20

**Comment by rstormsf** [comment]
#37 is created. @akolotov let me know how we should coordinate those 2. I guess they are related to each other.
1. Update to Native to ERC mode needs to be done
2. ERC20 to ERC20 could be added based on those contracts. 

What do you think?

**Comment by akolotov** [comment]
Could we consider this issue as addressed?

**Comment by patitonar** [comment]
@akolotov Yes, this issue is already addressed on `develop` branch.

**Comment by akolotov** [comment]
Thanks. Closing this issue.
