### ISSUE TITLE
Update ABI and event names, method names for v2.1 contract version

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/bridge-nodejs#37]
Latests contracts that have 2 bridge modes:
https://github.com/poanetwork/poa-bridge-contracts/tree/refactor_v1

Things to change:

Native to ERC:

| Previous Name  | Event or method | New Name | Home/Foreign|
| ------------- | ------------- |----------------|---------------|
| deposit  | method | executeSignatures | Foreign | 
| Deposit  | event | UserRequestForSignature | Home |
| withdraw | method | executeAffirmation|  Home  |
| Withdraw | event |  UserRequestForAffirmation | Foreign |
| submitSignature  | method | submitSignature - not changed | 
| CollectedSignatures | event | CollectedSignatures - not changed |

ERC20 TO ERC20 Mode
Deposits: 
User send a tx to ForeignBridge address, hence `Transfer` event is fired on Client's ERC20 contract. 
A validator listens for this event, and executes `executeAffirmation` method on HomeBridge, hence minting ERC677 token.
Withdrawals:
User send a tx to HomeBridge address, hence `UserRequestForSignature ` event is fired. 
A validator listens for this event, and executes `submitSignature` method on HomeBridge.
Then once `CollectedSignatures` is fired, a user executes `executeSignatures` method on Foreign Bridge, hence unlocking Client's ERC20 and sending it back to user.

**Comment by akolotov** [comment]
Could we consider this issue as addressed?

**Comment by patitonar** [comment]
@akolotov Yes, this issue is already addressed on `develop` branch.

**Comment by akolotov** [comment]
Thanks. Closing this issue.
