### ISSUE TITLE
Take required message length from the bridge contract

### ISSUE THREAD

**Issue by akolotov** [poanetwork/bridge-nodejs#56]
Currently `bridge-nodejs` calculating required length of the message which is needed to be signed by a validator. 

https://github.com/poanetwork/bridge-nodejs/blob/afa4b358476713aac2b90bbd1240c3d5f4ef0944/src/utils/message.js#L22

Since the correctness of the message is mostly required by bridge contracts, it is logical to get the required length of the message from contracts in order to eliminate possible issues related to desynchronization between contracts and `bridge-nodejs`.
The contracts contain the corresponding method for this:

https://github.com/poanetwork/poa-bridge-contracts/blob/98dbe5f2f94be2d26789fdf00c02748f5a233355/contracts/libraries/Message.sol#L67-L69

**Comment by fvictorio** [comment]
As far as I know, we can't use the `Message` library directly, so I added a method `requiredMessageLength` to the `BasicHomeBridge` contract. I will create a pull request in the contracts repository with this change, and another that uses it in this repo.
