### ISSUE TITLE
Improvements in gas price management

### ISSUE THREAD

**Issue by akolotov** [poanetwork/bridge-nodejs#6]
At this moment the code is written as so:
1. try to get gas price from the oracle
https://github.com/poanetwork/bridge-nodejs/blob/a23ecb78572f3e1928d9129eff8d4118b2618b57/src/gasPrice.js#L9
2. if the oracle is not accessible, the value from configuration file is used
https://github.com/poanetwork/bridge-nodejs/blob/a23ecb78572f3e1928d9129eff8d4118b2618b57/src/gasPrice.js#L14

There are few issues here:
1. The same oracle is used for both sides: Home and Foreign although it is assumed that these are two different networks and gas price for them could be different.
2. The fallback value is the same for both networks.

In order to address these issues the following is suggested to be implemented as result of previous discussion (https://github.com/poanetwork/poa-bridge/issues/16#issuecomment-386784045):

1. The following options to allow configure a JSON source of gas price should be available in the configuration file:
```
HOME_GAS_PRICE_ORACLE_URL = "https://gasprice.poa.network/"
HOME_GAS_PRICE_SPEED_TYPE = "fast"
HOME_GAS_PRICE_UPDATE_TIMEOUT = 600
FOREIGN_GAS_PRICE_ORACLE_URL = "https://gasprice.poa.network/"
FOREIGN_GAS_PRICE_SPEED_TYPE = "fast"
FOREIGN_HOME_GAS_PRICE_UPDATE_TIMEOUT = 600
```
Expecting that the gas price oracle will return information in the following form:
```
{"block_number":5559089,"block_time":14.824,"instant":50.0,"standard":4.0,"slow":2.0,"fast":5.0,"health":true}
```
And `HOME_GAS_PRICE_UPDATE_TIMEOUT` and `FOREIGN_HOME_GAS_PRICE_UPDATE_TIMEOUT` mean how often the corresponding oracle is requested to get updates.

2. If a request to the corresponding oracle is failed, the gas price needs to be requested from the corresponding contract by calling `gasPrice()` (https://github.com/poanetwork/poa-bridge-contracts/blob/93969cd934190649d42691f054676d0d16a9777e/contracts/upgradeable_contracts/U_BasicBridge.sol#L29) 

3. If the value from contract cannot be obtained the latest known value of gas price should be used.

4. Gas price obtained by either one of the way presented in 1, 2 or 3 will be considered as the cached gas price value.

4. In order to reduce number of requests to the oracles, transactions should be constructed with cached gas price value instead of sending request to the oracle for every transaction.

**Comment by rstormsf** [comment]
I'd say that HOME side could be hardcoded to '1' gwei easily.
only Foreign side should use gasprice oracle
