### ISSUE TITLE
Insecure connection message confusing if only one of URLs specifies HTTP link

### ISSUE THREAD

**Issue by akolotov** [poanetwork/bridge-nodejs#84]
If the configuration like the following is used:
```
ALLOW_HTTP=yes
HOME_RPC_URL=http://25.16.44.140
FOREIGN_RPC_URL=https://sokol.poa.network
```
The following message is displayed for the affirmation requests watcher if it does not work through `HOME_RPC_URL`:

```
{"level":40,"time":1537969077356,"msg":"You are using http (http://25.16.44.140). In production https must be used instead.","validator":"0xe4C28...32640c33","name":"watcher-erc-affirmation-request","v":1}
```

Consider to make the message more clear to avoid any confusion.

**Comment by fvictorio** [comment]
I'm not sure I understand this. What should be said in the message?

**Comment by akolotov** [comment]
The watcher of `affirmation-request` listens to Foreign network. Therefore, it uses `FOREIGN_RPC_URL` (https://sokol.poa.network) to communicate to the node. But the message says that `http://25.16.44.140` is used. This confused me because I started to think that set incorrect RPC URL for Foreign network.
