### ISSUE TITLE
Getting number of required signatures from CollectedSignatures event

### ISSUE THREAD

**Issue by akolotov** [poanetwork/bridge-nodejs#9]
At the current moment the number of required signatures which needs to be fetched to relay deposit transaction to Foreign network is taken from `HomeBridge` contract by calling `requiredSignatures`.

https://github.com/poanetwork/bridge-nodejs/blob/a23ecb78572f3e1928d9129eff8d4118b2618b57/src/processCollectedSignatures.js#L75

It could lead to situations when the number of required signatures used to approve the transaction relay is different from the actual number of required signatures in the contract. For example, it could happen when a validator was added or removed before the corresponding `CollectedSignatures` event triggered. 

In order to get rid of possible issues related inconsistencies between `requiredSignatures` value in the contract and number of signatures approved the corresponding deposit it was decided to extend `CollectedSignatures` event to contain number of collected signatures (https://github.com/poanetwork/poa-bridge-contracts/pull/42). So, the corresponding changes are required on the sever's side: the number of collected signatures should be extracted from the event data and used to fetch correct number of signatures from the contract.

**Comment by rstormsf** [comment]
it's done, so we should get rid of the  call and use 3rd argument from CollectedSignatures event

**Comment by akolotov** [comment]
needs to be confirmed if it is addressed in new version of bridge

**Comment by patitonar** [comment]
This issue was resolved as part of the new bridge architecture on #25 

https://github.com/poanetwork/bridge-nodejs/blob/819aa90993237e4c8a19ab5dfb6a406a492322ae/src/events/processCollectedSignatures.js#L28-L32

**Comment by akolotov** [comment]
Great! Thanks!
